const EmployeeData = [
    {
        matricule:'1',
          nom:'yosri',
          prenom:'aaaaaaa',
          datenaiss:null,
          lieu:'aaaaaaa',
          nationnalite:'aaaaaaa',
          NCin:'aaaaaaa',
          lieuC:'aaaaaaa',
          dateC:null,
          adresse:'aaaaaaa',
          Ntel:'aaaaaaa',
          dateEmb:null,
          sexe:'aaaaaaa',
          college:'aaaaaaa',
          dateEmbGrp:null,
          creditB:4444,
          creditS:4444,
        },{ matricule:'2',
          nom:'hamadi',
          prenom:'aaaaaaa',
          datenaiss:null,
          lieu:'aaaaaaa',
          nationnalite:'aaaaaaa',
          NCin:'aaaaaaa',
          lieuC:'aaaaaaa',
          dateC:null,
          adresse:'aaaaaaa',
          Ntel:'aaaaaaa',
          dateEmb:null,
          sexe:'aaaaaaa',
          college:'aaaaaaa',
          dateEmbGrp:null,
          creditB:44444,
          creditS:44444,
      }
];

export { EmployeeData };
